### ISSUE TITLE
Expose CSS tokens

### ISSUE THREAD

**Issue by MaceWindu** [AngleSharp/AngleSharp.Css#10]
It would be nice if you can make CSS tokens public.
In my case I need to extract urls from css, but required functionality (access to tokens) is currently marked as internal.
Right now I use ExCss project (https://github.com/TylerBrinks/ExCSS) for that task, but it wasn't updated in ages and contain critical bugs.

**Comment by FlorianRappl** [comment]
Are you sure you want the tokens? Working with the tokens is cumbersome and the tokens are thrown away anyway. I think what you are after is an improved object model that gives you easier access to desired information.

**Comment by MaceWindu** [comment]
Well, right, I need access to typed property value, not just a string.

**Comment by MaceWindu** [comment]
I've checked recent version and referenced commit and not sure how it can solve my issue (read all urls from css) - all I can get is a text of css style rule, but not typed values for rule properties.

**Comment by FlorianRappl** [comment]
The object model is rich now (though not exposed due to an unstable API, which will change in a future release) and this way you can get it (currently via reflection - in the future release directly, i.e., via a tree traversal / helper that will be delivered). If its a primitive value (e.g., for `background-image`) you can just get the CSS value (not the text, but the `ICssValue`, which is already exposed). What you look for is called a `UrlReference` (name subject for change). It has a property called `Path`, which gives you a string.

HTH!

(sorry for the incomplete solution, but I did not want to expose the full object model before not having reached a stable, i.e., non-breaking, state).

**Comment by MaceWindu** [comment]
Thanks, will try it next week again. Tried today with old approach with making some types public and failed as interrnal types changed alot
