### ISSUE TITLE
Remove dependency on System.Text.Encoding.CodePages for non dotnet core release

### ISSUE THREAD

**Issue by GieltjE** [AngleSharp/AngleSharp.Css#13]
Idealy the normal oldschool dotnet version should not depend on dotnetcore libraries.

**Comment by FlorianRappl** [comment]
Right - can you make a PR please? Thanks!

**Comment by GieltjE** [comment]
Seems to compile and run just fine without the "System.Text.Encoding.CodePages" nuget package (for botch dotnet core and normal)

**Comment by FlorianRappl** [comment]
--> I think you refer to .NET!

If you would do the same for .NET Core (see running unit tests) you will see that all (with exception of those not requiring any encoding, which is the minority) tests fail.

**Comment by FlorianRappl** [comment]
@GieltjE should the issue really be closed? I think the point for the normal .NET Framework is still valid.

**Comment by GieltjE** [comment]
Sorry don't have the time nor energy to fix this (working 60 hours a week), haven't found any code dependencies on the mentioned library, compiles just fine on my machine without.

**Comment by FlorianRappl** [comment]
Completely understood - we all have our normal jobs and I have plenty of projects myself; that's just how OSS development works (you have volunteers who are willing to spend the extra time for community benefit).

Again, compiling (for a .NET Core app) is not the problem - the issue is running without. Everything fails here due to the unresolved initializer pointing to CodePages. Just to emphasize again - this is all .NET Core; on standard .NET FX you don't face this issue hence why I requested the issue to be reopened.

**Comment by FlorianRappl** [comment]
Will be done in 0.12.
