### ISSUE TITLE
Removing properties causes empty value when serializing

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp.Css#14]
Example:

```C#
var p = new HtmlParser(new HtmlParserOptions(), BrowsingContext.New(new Configuration().WithCss()));
var dom = p.ParseDocument(@"<html><body><div style=""background: 0;"">Test</div></body></html>");
var div = dom.QuerySelector("div");
var style = div.GetStyle();
style.RemoveProperty("background-position-x");
style.RemoveProperty("background-position-y");
var css = style.CssText; // -> "background: "
```

FWIW, both Chrome and Firefox output `"background-color: rgba(0, 0, 0, 0); background-repeat: repeat; background-attachment: scroll; background-image: none; background-size: auto auto; background-origin: padding-box; background-clip: border-box;"` in this case.

**Comment by FlorianRappl** [comment]
The essential bug is fixed in devel, however, I think we should not output `initial` ever. Instead, the related value (that is behind setting "initial") should be already in there -> leading to consistent output with the browser.

Implementing this will take a while; not because it is very difficult, but because there are many many CSS declarations.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
