### ISSUE TITLE
Some link tags cannot be casted to ILinkStyle

### ISSUE THREAD

**Issue by gandolh** [AngleSharp/AngleSharp.Css#149]
# Bug Report

## Description
document.GetStyleSheets().OfType<ICssStyleSheet>() has a problem with fetching all the css resources.
 I tried to fetch all the CSS from a website and some link tags couldn't be found by `document.GetStyleSheets().OfType<ICssStyleSheet>()`. I tried to get all the links tag that has an rel="stylesheet" and exclude those found by GetStyleSheets. In the end there was one link tag that couldn't be casted to ILinkStyle (so it was skipped by GetStyleSheets) and couldn't get the  ICssStyleSheet object from it. 
 I solved this by manually fetching with .Net HttpClient the css resource using the href tag but this seems unoptimal.
## Steps to Reproduce
Minimal reproducable code:
https://gist.github.com/gandolh/a810158fc79ccbe476e99a600ca1fd1b

**Comment by FlorianRappl** [comment]
Sorry I don't see a real MWE code to reproduce this. Examples that work with an external URL are not considered valid, as they might change / might already have changed / do a lot of things which might be unnecessary for the reproduction.

If you can show some code / what the issue is then we can maybe help you.

Also, I get the same results / no different sheets running your code:

![image](https://github.com/AngleSharp/AngleSharp.Css/assets/1766191/a417a400-eccf-4f1f-94b0-44378892f40b)

There are 2 style sheets and both are there. So it's totally fine.
