### ISSUE TITLE
The default style sheet in CssStylingService.Default is ignored

### ISSUE THREAD

**Issue by poizan42** [AngleSharp/AngleSharp.Css#21]
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (if its an issue with the core library, please report to `AngleSharp` directly)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

CssStylingService defines a Default style sheet (which by default is the one specified by W3C), and allows changing this with SetDefault. However this value is never read anywhere and nothing supplies default css rules.

### Steps to Reproduce

Compile and run a program calling DefaultStyleSheetTest:

```CSharp
    private static void DefaultStyleSheetTest()
    {
      var browsingContext = BrowsingContext.New(Configuration.Default.WithCss());
      var htmlParser = browsingContext.GetService<IHtmlParser>();
      var document = htmlParser.ParseDocument("<html><body><b>Hello, World!</b></body></html>");
      var boldStyle = document.Body.FirstElementChild.ComputeCurrentStyle();
      Console.WriteLine(boldStyle.GetFontWeight());
    }
```

**Expected behavior:** "bolder" should be printed to the console

**Actual behavior:** an empty string is printed to the console

**Environment details:** .NET 4.7.2, Windows 10.0.18334.1

### Possible Solution

Expose CssStylingService.Default through the IStylingService interface. Make StyleExtensions.GetStyleSheets yield the DefaultStyle as the first style sheet (given that the IStylingService can be accessed and has Default and it is not disabled.

**Comment by FlorianRappl** [comment]
Yep I think it needs to be connected. Potentially, this should be included in the configuration (via, e.g., the `ICssStyleSheet`) and *all* registered stylesheets should be taken. If we follow this there is no need for a default stylesheet property (or exposing it). By default, we would insert the given default stylesheet on `WithCss`. How does that sound?

**Comment by poizan42** [comment]
I think it makes good sense to be able to supply more than one default stylesheet to the context, e.g. the base W3C stylesheet and a user customization stylesheet.

But I feel that registering them directly in Services is going to be confusing, as a stylesheet isn't really a service. Maybe add a IDefaultStyleSheetProviderService or something like that, if IStylingService shouldn't be the one to take care of that.

**Comment by FlorianRappl** [comment]
Yeah that reasonable, however, note that configuration changed with AngleSharp 0.10 and is not for services alone, but just for a general configuration (placing any kind of instances that may be picked up on a general note).

The whole notion for providers, services, factories, etc. just follows from the registered instances.

Maybe a better location pops up, otherwise I would go with the configuration.

**Comment by FlorianRappl** [comment]
Landed in `devel`.

There is a new `ICssDefaultStyleSheetProvider` that is responsible for setting the stylesheet. `WithCss` sets this if nothing is found.

I also added some extensions to allow appending string sources ("sources of a custom stylesheet").

Of course, the bug is also fixed (thanks for the test!).
