### ISSUE TITLE
CSS value normalizing?

### ISSUE THREAD

**Issue by tiesont** [AngleSharp/AngleSharp.Css#9]
I realize the devel branch is basically alpha, so this is a "is this the behavior going forward?" type of question.

Basically, I'm curious if it's intentional that values such as `background: 0` or `color: black` become `background: left` and `color: rgba(0, 0, 0, 1)`, respectively. The end result is functionally equivalent, but given that, is there a reason to convert the source value?

I can understand splitting the AngleSharp project into separate projects, but my expectation was that the output would be the same in AngleSharp.Css as it is currently in the combined project.

For reference, this question originates from this issue in HtmlSanitzer: https://github.com/mganss/HtmlSanitizer/issues/117.

**Comment by FlorianRappl** [comment]
`This is a good question and the answer is as follows: If a value is known, it is converted to an object. This object has a fixed representation (which could be understood as some normalization). Thus, it will not have any string assigned, but rather computes the string if demanded.

This is highly helpful for, e.g., a renderer, and not so helpful for the tooling as in your question. However, note that you are still free to override this behavior.

You could do the following two things:

1. Just deactivate value creation at all - no validation here. It will result in generic objects which transport the original string.
2. Write your own value creator. This one could use the creator from the library, but will only use it for validation purposes. If the value is correctly validated, the generic object from 1. is passed on. Thus you have the best of both worlds for the helper tool.

Generally, it should be very simple to compose AngleSharp.Css to your needs. The default one is set in such a way to mimic the behavior of browsers as close as possible, but further use cases are welcome and should be possible without much hazzle.

(Remark: Actually, also AngleSharp today is performing this kind of normalization, but it can be turned off via a simple flag. In AngleSharp.Css this is much more flexible and you just insert a different interface to handle it.)

**Comment by FlorianRappl** [comment]
Yes we sometimes simplify a little bit more. Every shorthand has the possibility to reject a combination of their longhands - the `background` in this case does not refuse if only a `background-color` longhand has been set. This is because it is still valid.

As far as I know this is no where specified and browsers are free to implement this on their own. I am not sure if implementations in this case vary (between the evergreen browsers), but I am sure that in general browsers are not uniform w.r.t. CSS longhand / shorthand declaration serialization.

Is this a problem for you @mganss? Do you have any suggestions or how would you improve the situation? What is your ideal API here? Thanks for any suggestions or feedback!

**Comment by mganss** [comment]
I'm currently updating HtmlSanitizer to AngleSharp 0.10.0 and noticed a large number of test cases fail due to this issue. I could just adapt the expected output to the new actual values, but in many cases it feels like violating [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) too much.

Ideally, AngleSharp.Css would mimic browser behavior as closely as possible. I don't know if there's a specification, but in all cases I tested Chrome and Firefox behaved identically.

The biggest problem is that invalid values result in `initial` being output. For example, `top: test` results in `top: initial`. Browsers drop the invalid property completely, i.e. they output "".

**Comment by mganss** [comment]
I feel your pain and admire the herculean effort you put into AngleSharp. I have a number of smaller projects on GitHub which I can barely keep up with 🙄 
Can you point out where I should look in order to implement your suggestion 2 from above (write your own value creator)?
